### ISSUE TITLE
[Bug] Problem using customer rules definition

### ISSUE THREAD

**Issue by paradinha** [MarketSquare/robotframework-robocop#561]
### What happened?

Using the robocop tool to perform static analisys, using the predefined rules, I'n not facing any problems with it.
Teh problem is when attempt to follow the guidelines to include some custom rules to project, some problems with import of RuleParam from robocop rules, or even the rules dictionary containing the rules definition to the new checkers to be implemented.

In fact, I'm just attempting to use the code examples mentioned in the documentation (https://robocop.readthedocs.io/en/stable/external_rules.html), and I'm facing problems with RuleParam import, rule name atribute

Problem when attempting to import the 
`    from robocop.rules import Rule, RuleParam, RuleSeverity
ImportError: cannot import name 'RuleParam' from 'robocop.rules' (/home/maltapar/tmp/robocop-tests/.venv-linter/lib/python3.8/site-packages/robocop/rules.py)`

Problem with name atribute in rule: 
`  File "/home/maltapar/tmp/robocop-tests/customRules/myRule1.py", line 5, in <module>
    "9999": Rule(rule_id="9999", name="dummy-in-name", msg="There is 'Dummy' in test case name", severity=RuleSeverity.WARNING)
TypeError: __init__() got an unexpected keyword argument 'name'`

I attached a simple demo project where you can replicate the problems that I'm facing:
[robocop-tests.zip](https://github.com/MarketSquare/robotframework-robocop/files/8088540/robocop-tests.zip)

I create a script that prepares a setup with python vitual enviroment, installing the robotframework==3.2.2 and robotframework-robocop==1.12.0, and runs the robocop statis analisys from the testcases folder.

$ python --version
Python 3.8.10

$ robot --version
Robot Framework 3.2.2 (Python 3.8.10 on linux)

$ robocop --version
1.12.0

### Operating System

Windows + WSL2

### Robocop version

1.12.0

**Comment by bhirsz** [comment]
`RuleParam` was introduced in Robocop 2.0. I have almost completely reworded how we define rules in Robocop 2.0 (mostly to make it easier to add new rules, previously it was using tuples instead of proper classes). It's not yet released - hopefully we can do release before Robot Framework 5.0 release. So the problem is that you saw the documentation for newest version that's not yet released. When I enter https://robocop.readthedocs.io/en/stable/external_rules.html it still describes old way. New way is only available at https://robocop.readthedocs.io/en/latest/external_rules.html . (stable -> latest). 


I think it would be best if you work with Robocop 2.0 to not waste time overwriting your custom rules when it will be released (matter of 1-2 weeks). For now you can try to install development version of Robocop from the source :
```
pip install https://github.com/MarketSquare/robotframework-robocop/archive/master.zip
```

**Comment by paradinha** [comment]
Hi @bhirsz, thanks for the quick answer on this topic. 
In fact with the development version, those problems are outadate. 

We are in the process of adopting/migrating to this tool, so we will follow your sugestion to start preparing everything based on the new version to come.
Best regards.
